<script lang="ts">
  import { extractLayer, index1d } from "./grid";
  import { debug, dest_x, dest_y, dim, start_x, start_y } from "./stores";

  export let key: number;
  export let grid: string[][];
  export let drawingWalls: boolean, settingStart: boolean, settingEnd: boolean;
  export let savedWalls: boolean[][] | null;

  const addWall = (idx1d: number) => {
    if (drawingWalls) {
      const [i, j] = index1d(idx1d, $dim);
      if (grid[i][j] == "") grid[i][j] = "X";
    }
  };
</script>

<div
  class="border border-slate-500 w-full h-8 m-0 transition-all duration-150"
  class:visited={grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]] == "v"}
  class:wall={grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]] == "X"}
  class:path={grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]] == "p"}
  class:start={grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]] == "s"}
  class:dest={grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]] == "d"}
  class:hover:cursor-move={grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]] ==
    "d" ||
    grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]] == "s" ||
    settingStart ||
    settingEnd}
  class:hover:bg-red-600={settingStart}
  class:hover:bg-green-600={settingEnd}
  class:hover:opacity-80={settingStart || settingEnd}
  class:hover:scale-110={settingStart || settingEnd}
  on:mousedown={() => {
    const [i, j] = index1d(key, $dim);

    // handle a click on the start square
    if (grid[i][j] == "s") {
      grid[i][j] = "";
      settingStart = true;
    } else if (grid[i][j] == "d") {
      grid[i][j] = "";
      settingEnd = true;
    }
    // handle a click on the destination square when moving it
    else if (settingEnd) {
      if (grid[i][j] == "") {
        settingEnd = false;
        $dest_x = i;
        $dest_y = j;
      }
    }
    // handle a click on the start square when moving it
    else if (settingStart) {
      if (grid[i][j] == "") {
        settingStart = false;
        $start_x = i;
        $start_y = j;
      }
    } else {
      drawingWalls = true;
      addWall(key);
    }
  }}
  on:mouseup={() => {
    const [i, j] = index1d(key, $dim);
    if (settingStart) {
      settingStart = false;
      if (grid[i][j] == "") {
        $start_x = i;
        $start_y = j;
      }
    } else if (settingEnd) {
      settingEnd = false;
      if (grid[i][j] == "") {
        $dest_x = i;
        $dest_y = j;
      }
    }

    drawingWalls = false;
    savedWalls = extractLayer(grid, "X");
  }}
  on:mouseenter={() => {
    addWall(key);
  }}
>
  {#if $debug}
    {grid[index1d(key, $dim)[0]][index1d(key, $dim)[1]]}
  {/if}
</div>

<style lang="postcss">
  .visited {
    @apply bg-sky-600 scale-up-center;
  }
  .path {
    @apply bg-purple-400 scale-up-center;
  }
  .wall {
    @apply bg-black;
  }
  .start {
    @apply bg-red-600;
  }
  .dest {
    @apply bg-green-600;
  }

  .scale-up-center {
    -webkit-animation: scale-up-center 0.3s cubic-bezier(0.39, 0.575, 0.565, 1)
      both;
    animation: scale-up-center 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2022-12-23 1:41:8
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-up-center
 * ----------------------------------------
 */
  @-webkit-keyframes scale-up-center {
    0% {
      -webkit-transform: scale(0.1);
      transform: scale(0.1);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
  @keyframes scale-up-center {
    0% {
      -webkit-transform: scale(0.1);
      transform: scale(0.1);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
</style>
