<script lang="ts">
  import { extractLayer, index1d } from "./grid";
  import { debug, dest_x, dest_y, dim, start_x, start_y } from "./stores";

  export let key: number;
  export let grid: string[][];
  export let drawingWalls: boolean, settingStart: boolean, settingEnd: boolean;
  export let savedWalls: boolean[][] | null;

  const [x, y] = index1d(key, $dim);

  const addWall = () => {
    if (drawingWalls) {
      if (grid[x][y] == "") grid[x][y] = "X";
    }
  };
</script>

<div
  class="border border-slate-500 w-full h-8 m-0 transition-all duration-150"
  class:visited={grid[x][y] == "v"}
  class:wall={grid[x][y] == "X"}
  class:path={grid[x][y] == "p"}
  class:start={grid[x][y] == "s"}
  class:dest={grid[x][y] == "d"}
  class:hover:cursor-move={grid[x][y] == "d" ||
    grid[x][y] == "s" ||
    settingStart ||
    settingEnd}
  class:hover:bg-red-600={settingStart}
  class:hover:bg-green-600={settingEnd}
  class:hover:opacity-80={settingStart || settingEnd}
  class:hover:scale-110={settingStart || settingEnd}
  on:mousedown={() => {
    // handle a click on the start square
    if (grid[x][y] == "s") {
      grid[x][y] = "";
      settingStart = true;
    } else if (grid[x][y] == "d") {
      grid[x][y] = "";
      settingEnd = true;
    }
    // handle a click on the destination square when moving it
    else if (settingEnd) {
      if (grid[x][y] == "") {
        settingEnd = false;
        [$dest_x, $dest_y] = [x, y];
      }
    }
    // handle a click on the start square when moving it
    else if (settingStart) {
      if (grid[x][y] == "") {
        settingStart = false;
        [$start_x, $start_y] = [x, y];
      }
    } else {
      drawingWalls = true;
      addWall();
    }
  }}
  on:mouseup={() => {
    if (settingStart) {
      settingStart = false;
      if (grid[x][y] == "") [$start_x, $start_y] = [x, y];
    } else if (settingEnd) {
      settingEnd = false;
      if (grid[x][y] == "") [$dest_x, $dest_y] = [x, y];
    }

    drawingWalls = false;
    savedWalls = extractLayer(grid, "X");
  }}
  on:mouseenter={addWall}
>
  {#if $debug}
    {grid[x][y]}
  {/if}
</div>

<style lang="postcss">
  .visited {
    @apply bg-sky-600 scale-up-center;
  }
  .path {
    @apply bg-purple-400 scale-up-center;
  }
  .wall {
    @apply bg-black;
  }
  .start {
    @apply bg-red-600;
  }
  .dest {
    @apply bg-green-600;
  }

  .scale-up-center {
    -webkit-animation: scale-up-center 0.3s cubic-bezier(0.39, 0.575, 0.565, 1)
      both;
    animation: scale-up-center 0.3s cubic-bezier(0.39, 0.575, 0.565, 1) both;
  }
  /* ----------------------------------------------
  * Generated by Animista on 2022-12-23 1:41:8
  * Licensed under FreeBSD License.
  * See http://animista.net/license for more info. 
  * w: http://animista.net, t: @cssanimista
  * ---------------------------------------------- */

  /**
  * ----------------------------------------
  * animation scale-up-center
  * ----------------------------------------
  */
  @-webkit-keyframes scale-up-center {
    0% {
      -webkit-transform: scale(0.1);
      transform: scale(0.1);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
  @keyframes scale-up-center {
    0% {
      -webkit-transform: scale(0.1);
      transform: scale(0.1);
    }
    100% {
      -webkit-transform: scale(1);
      transform: scale(1);
    }
  }
</style>
